### ISSUE TITLE
Some value construction checks are too strict

### ISSUE THREAD

**Issue by jamesrhester** [cod-developers/cod-tools#12]
I've noticed the following overly strict value checks when running cod-tools against a dictionary (see the very end of [this run](https://github.com/jamesrhester/Powder_Dictionary/actions/runs/3148823655/jobs/5119769674))

1. The date time check is too strict compared to RFC3339: it appears that the letter 'Z' is excluded, as are certain offsets.
2. "0." is not recognised as a complex number
3. dictionary version appear not to allow pre-release numbering.

**Comment by vaitkus** [comment]
@jamesrhester, thank you for reporting this. To avoid having several discussions at once, I have created a separate issue for each topic:

- datetime: #13 
- complex numbers: #14
- version strings: #15

I will be happy to implement the necessary changes once we reach a consensus.

**Comment by vaitkus** [comment]
Closing this issue since it is now represented by individual issues for each topic.
