### ISSUE TITLE
ddlm_validate: '.0' is not recognised as a complex number

### ISSUE THREAD

**Issue by vaitkus** [cod-developers/cod-tools#14]
It was reported in a another issue (https://github.com/cod-developers/cod-tools/issues/12) that value '.0' is not recognised as a valid complex number.

While the DDLm reference dictionary does not specify an explicit syntax for complex numbers, at one point I had the opportunity to review a draft version of the "Construction and interpretation of CIF dictionaries" chapter from the upcoming ITC release which is a bit more clear about this:
```
CIF string should have form 'a [+-] bj' (whitespace optional) where a and b are interpreted as numbers.
```
Following this definition, complex value '.0' should be written as '.0 + 0j'. Does that seem reasonable?

If not, I would like to have some more explicit specifications on how the `Complex` data format should be expressed, e.g. if and when it is OK to omit the imaginary part, can the real part be omitted if it is 0, etc.

**Comment by jamesrhester** [comment]
You are correct that the draft version of that chapter explicitly requires an imaginary part. I think for simplicity we should stick with always having an explicit imaginary part and this issue can also be closed.
