### ISSUE TITLE
ddlm_validate: pre-release dictionary versions are marked as invalid

### ISSUE THREAD

**Issue by vaitkus** [cod-developers/cod-tools#15]
It was reported in a another issue (https://github.com/cod-developers/cod-tools/issues/12) that pre-release versions (e.g. "2.5.0-pre-2") are not recognised as valid.

The current version of the DDLm reference dictionary defines the 'Version' content type as:
```
Version digit string of the form <major>.<version>.<update>
```
Therefore, it does not *yet* formally permit pre-release versions. I recall that the whole pre-release versioning was written up in great detail in one of the draft documents, but I am not sure if it has been made "official" yet and if it can be referenced in the DDLm reference dictionary.

Alternatively, we could update the DDLm dictionary to state that the "Version" content type follows the general syntax of [semantic versioning](https://semver.org/spec/v2.0.0.html) version strings. Semantic versioning has a well defined grammar (Backus-Naur Form) and seems to be  compatible with the syntax of our pre-release versions. What do you think?

**Comment by jamesrhester** [comment]
I think this is a very good idea. This issue should be transferred to cif-core.

**Comment by vaitkus** [comment]
The issue was resolved in r9638.
