### ISSUE TITLE
pycodcif parser: is Python 3 supported?

### ISSUE THREAD

**Issue by blokhin** [cod-developers/cod-tools#5]
Cannot find any mention of Python 3 support. In my case, build fails with the typical message concerning the conflict of Python libraries of different versions:
```
.../pycodcif-0.8.9/cod-tools/src/components/pycodcif/pycodcif.c:315: undefined reference to `PyInt_FromLong'
build/temp.cygwin-2.8.0-i686-3.6/cod-tools/src/components/pycodcif/pycodcif.o: In function `extract_value':
.../pycodcif-0.8.9/cod-tools/src/components/pycodcif/pycodcif.c:66: undefined reference to `PyString_FromString'
build/temp.cygwin-2.8.0-i686-3.6/cod-tools/src/components/pycodcif/pycodcif.o: In function `extract_type':
.../pycodcif-0.8.9/cod-tools/src/components/pycodcif/pycodcif.c:112: undefined reference to `PyString_FromString'
```
but may be that's only my own environment issue.

**Comment by merkys** [comment]
@blokhin, you are right, Python 3 is not yet supported. Although maintaining Python 3 is not our top priority, I am planning to rewrite the bindings in a couple of months.

**Comment by blokhin** [comment]
Hi Andrius @merkys, do you have any updates on that? (Totally understand if not, this is the open-source world!)

**Comment by merkys** [comment]
Hi @blokhin, I am really close (couple of weeks) to achieving it. Most of the code proved to reusable, I just have to sort things out with the changes in Unicode representation.

**Comment by blokhin** [comment]
@merkys sorry for bothering, just making sure we're in sync...

**Comment by merkys** [comment]
Hi @blokhin. Code for Python3 is ready to use as of cod-tools v2.2 ([released](http://wiki.crystallography.net/cod-tools/) in source only for now). I'm on a vacation till the mid of Aug, but I will push Python3 bindings to PyPI once I get back.

**Comment by blokhin** [comment]
Many thanks. Appreciate that a lot (together with the hundreds of other real and potential users of your code!)

**Comment by blokhin** [comment]
@merkys please, could you push Python 2/3 bindings to PyPI?

**Comment by merkys** [comment]
@blokhin done, please try!

**Comment by blokhin** [comment]
Follow-up: swig dependency should be stated.
```
  Running setup.py install for pycodcif ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-m_dbil26/pycodcif/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-ki9fhpsq-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    running build_ext
    building 'pycodcif._pycodcif' extension
    swigging pycodcif.i to pycodcif_wrap.c
    swig -python -o pycodcif_wrap.c pycodcif.i
    unable to execute 'swig': No such file or directory
    error: command 'swig' failed with exit status 1
```

**Comment by merkys** [comment]
Thanks for spotting this! Do you have an idea how to do it in setup.py? GoogleSearch did not return any meaningful results.

**Comment by blokhin** [comment]
May be like this?
```python
p = subprocess.Popen(['swig'], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
result, err = p.communicate()
if p.returncode != 0:
    raise SystemExit('Please install swig toolchain')
```
